/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pastaFuncionario.Funcionario;
import pastaFuncionario.FuncionarioDados;
import pastaFuncionario.FuncionarioNegocio;

/**
 *
 * @author aluno
 *
 */
public class TelaEditarFuncionario extends javax.swing.JFrame {

    ArrayList<Funcionario> listaFuncionario = null;
    TelaShipping tA = null;

    public TelaEditarFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            FuncionarioDados dadosF = new FuncionarioDados();
            listaFuncionario = dadosF.listarFuncionario();
            for (Funcionario f1 : listaFuncionario) {
                modelo.addElement(f1.getNomeFuncionario());
            }
            cBEditarFuncionario.setModel(modelo);
            cBEditarFuncionario.setSelectedIndex(-1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cBEditarFuncionario = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditarFuncionario = new javax.swing.JTextField();
        jButtonAlterarFuncionario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Intro Inline", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Renomear funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        cBEditarFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cBEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 187, 34));

        jLabel2.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("De :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Para :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextFieldEditarFuncionario.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jTextFieldEditarFuncionario.setText("Novo nome funcionário");
        jTextFieldEditarFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEditarFuncionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEditarFuncionarioFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldEditarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 185, 34));

        jButtonAlterarFuncionario.setText("Alterar");
        jButtonAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 52));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Sem Título-2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, -1, -1));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEditarFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEditarFuncionarioFocusLost
        if (jTextFieldEditarFuncionario.getText().equals("")) {
            jTextFieldEditarFuncionario.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldEditarFuncionario.setText("Novo nome funcionário");
        }
        if (jTextFieldEditarFuncionario.getText() == null) {
            jTextFieldEditarFuncionario.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldEditarFuncionario.setText("Novo nome funcionário");
        }

    }//GEN-LAST:event_jTextFieldEditarFuncionarioFocusLost

    private void jTextFieldEditarFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEditarFuncionarioFocusGained
        if (jTextFieldEditarFuncionario.getText().equals("Novo nome funcionário")) {
            jTextFieldEditarFuncionario.setText("");
        }

        if (jTextFieldEditarFuncionario.getText().equals("")) {
            jTextFieldEditarFuncionario.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }
    }//GEN-LAST:event_jTextFieldEditarFuncionarioFocusGained

    private void jButtonAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFuncionarioActionPerformed
        try {
            if (jTextFieldEditarFuncionario.getText().equals("Novo nome funcionário")) {
                jTextFieldEditarFuncionario.setText(null);
            }
            if (cBEditarFuncionario.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Favor selecionar o funcionário ");
                return;
            }
            Funcionario f = this.listaFuncionario.get(cBEditarFuncionario.getSelectedIndex());
            f.setNomeFuncionario(jTextFieldEditarFuncionario.getText());
            FuncionarioNegocio fN = new FuncionarioNegocio();
            fN.alterarFuncionario(f);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            FuncionarioDados dadosF = new FuncionarioDados();
            listaFuncionario = dadosF.listarFuncionario();
            for (Funcionario f1 : listaFuncionario) {
                modelo.addElement(f1.getNomeFuncionario());
            }
            cBEditarFuncionario.setModel(modelo);
            cBEditarFuncionario.setSelectedIndex(-1);

            tA = new TelaShipping(f);
            tA.atualizarFuncionario();
            jTextFieldEditarFuncionario.setText("");
            cBEditarFuncionario.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }


    }//GEN-LAST:event_jButtonAlterarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cBEditarFuncionario;
    private javax.swing.JButton jButtonAlterarFuncionario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEditarFuncionario;
    // End of variables declaration//GEN-END:variables
}
