/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pastaSetor.Setor;
import pastaSetor.SetorDados;
import pastaSetor.SetorNegocio;

/**
 *
 * @author Jerson e Pedro
 */
public class TelaEditarSetor extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovoSetor
     */
    ArrayList<Setor> listaSetor = null;
    
    public TelaEditarSetor() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            SetorDados dadosS = new SetorDados();
            listaSetor = dadosS.listarSetor();
            for (Setor s1 : listaSetor) {
                modelo.addElement(s1.getNomeSetor());
            }
            jComboBoxSelecionarSetor.setModel(modelo);
            jComboBoxSelecionarSetor.setSelectedIndex(-1);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEditarSetor = new javax.swing.JTextField();
        jButtonEditarSetor = new javax.swing.JButton();
        jComboBoxSelecionarSetor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Intro Inline", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Renomear Setor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        jTextFieldEditarSetor.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jTextFieldEditarSetor.setText("Novo nome setor");
        jTextFieldEditarSetor.setToolTipText("");
        jTextFieldEditarSetor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEditarSetorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEditarSetorFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldEditarSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 127, 32));

        jButtonEditarSetor.setText("Alterar");
        jButtonEditarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSetorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 80, 33));

        jComboBoxSelecionarSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSelecionarSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 127, 32));

        jLabel2.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("De :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Para :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Sem Título-2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 320, -1));

        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSetorActionPerformed
        try {
            if (jTextFieldEditarSetor.getText().equals("Novo nome setor")) {
                jTextFieldEditarSetor.setText(null);
            }
            if (jComboBoxSelecionarSetor.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Favor selecionar o setor ");
                return;
            }
            Setor s = this.listaSetor.get(jComboBoxSelecionarSetor.getSelectedIndex());
            s.setNomeSetor(jTextFieldEditarSetor.getText());
            SetorNegocio sN = new SetorNegocio();
            sN.alterarSetor(s);
            
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            SetorDados dadosS = new SetorDados();
            listaSetor = dadosS.listarSetor();
            for (Setor s1 : listaSetor) {
                modelo.addElement(s1.getNomeSetor());
            }
            jComboBoxSelecionarSetor.setModel(modelo);
            jComboBoxSelecionarSetor.setSelectedIndex(-1);
            jTextFieldEditarSetor.setText("");
            jComboBoxSelecionarSetor.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonEditarSetorActionPerformed

    private void jTextFieldEditarSetorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEditarSetorFocusLost
        if (jTextFieldEditarSetor.getText().equals("")) {
            jTextFieldEditarSetor.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldEditarSetor.setText("Novo nome setor");
        }
        if (jTextFieldEditarSetor.getText() == null) {
            jTextFieldEditarSetor.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldEditarSetor.setText("Novo nome setor");
        }

    }//GEN-LAST:event_jTextFieldEditarSetorFocusLost

    private void jTextFieldEditarSetorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEditarSetorFocusGained
        if (jTextFieldEditarSetor.getText().equals("Novo nome setor")) {
            jTextFieldEditarSetor.setText("");
        }
        
        if (jTextFieldEditarSetor.getText().equals("")) {
            jTextFieldEditarSetor.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }

    }//GEN-LAST:event_jTextFieldEditarSetorFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarSetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditarSetor;
    private javax.swing.JComboBox jComboBoxSelecionarSetor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEditarSetor;
    // End of variables declaration//GEN-END:variables
}
