/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pastaFuncionario.Funcionario;
import pastaFuncionario.FuncionarioNegocio;
import pastaSetor.Setor;
import pastaSetor.SetorDados;

/**
 *
 * @author Jerson e Pedro
 */
public class TelaNovoFuncionario extends javax.swing.JFrame {

    ArrayList<Setor> listaSetor = null;
    TelaShipping tA = null;

    public TelaNovoFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            SetorDados dadosS = new SetorDados();
            listaSetor = dadosS.listarSetor();
            for (Setor s1 : listaSetor) {
                modelo.addElement(s1.getNomeSetor());
            }
            cBNomeSetor.setModel(modelo);
            cBNomeSetor.setSelectedIndex(-1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNovoFuncionario = new javax.swing.JTextField();
        jButtonCadastrarNovoFuncionario = new javax.swing.JButton();
        cBNomeSetor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Intro Inline", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Novo Funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        jTextFieldNovoFuncionario.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jTextFieldNovoFuncionario.setText("Nome novo funcionário");
        jTextFieldNovoFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNovoFuncionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNovoFuncionarioFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldNovoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 145, 33));

        jButtonCadastrarNovoFuncionario.setText("Cadastrar");
        jButtonCadastrarNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrarNovoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        cBNomeSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cBNomeSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 145, 33));

        jLabel2.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Slim Joe", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Setor :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Sem Título-2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -70, -1, -1));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoFuncionarioActionPerformed

        try {
            if (jTextFieldNovoFuncionario.getText().equals("Nome novo funcionário")) {
                jTextFieldNovoFuncionario.setText(null);
            }
            if (cBNomeSetor.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Favor selecionar um Setor ");
                return;
            }
            Funcionario f = new Funcionario();
            Setor s = this.listaSetor.get(cBNomeSetor.getSelectedIndex());
            f.setSetor(s);
            f.setNomeFuncionario(jTextFieldNovoFuncionario.getText());
            FuncionarioNegocio fN = new FuncionarioNegocio();
            fN.cadastrarFuncionario(f);
            tA = new TelaShipping(f);
            tA.atualizarFuncionario();
              jTextFieldNovoFuncionario.setText("");
              cBNomeSetor.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_jButtonCadastrarNovoFuncionarioActionPerformed

    private void jTextFieldNovoFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNovoFuncionarioFocusLost
        if (jTextFieldNovoFuncionario.getText().equals("")) {
            jTextFieldNovoFuncionario.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldNovoFuncionario.setText("Nome novo funcionário");
        }
        if (jTextFieldNovoFuncionario.getText() == null) {
            jTextFieldNovoFuncionario.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldNovoFuncionario.setText("Nome novo funcionário");
        }

    }//GEN-LAST:event_jTextFieldNovoFuncionarioFocusLost

    private void jTextFieldNovoFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNovoFuncionarioFocusGained
        if (jTextFieldNovoFuncionario.getText().equals("Nome novo funcionário")) {
            jTextFieldNovoFuncionario.setText("");
        }

        if (jTextFieldNovoFuncionario.getText().equals("")) {
            jTextFieldNovoFuncionario.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }


    }//GEN-LAST:event_jTextFieldNovoFuncionarioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cBNomeSetor;
    private javax.swing.JButton jButtonCadastrarNovoFuncionario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNovoFuncionario;
    // End of variables declaration//GEN-END:variables
}
