/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shipping;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import pastaFuncionario.Funcionario;
import pastaFuncionario.FuncionarioDados;

/**
 *
 * @author Edson
 */
public class TelaShipping extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlpha
     */
    public TelaShipping() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTableRecebidos.requestFocus();
        try {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            FuncionarioDados dadosF = new FuncionarioDados();
            ArrayList<Funcionario> listaFunc = null;
            
            listaFunc = dadosF.listarFuncionario();
            for (Funcionario f1 : listaFunc) {
                modelo.addElement(f1.getNomeFuncionario());
            }
            cBDestinatario.setModel(modelo);
            cBDestinatario.setSelectedIndex(-1);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        abaMenu = new javax.swing.JTabbedPane();
        abaMenuRecebidos = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecebidos = new javax.swing.JTable();
        abaMenuEnviados = new javax.swing.JDesktopPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        abaMenuNovo = new javax.swing.JDesktopPane();
        cBDestinatario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLink = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoNovoProtocolo = new javax.swing.JMenuItem();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuEditarFuncionario = new javax.swing.JMenuItem();
        menuEditarSetor = new javax.swing.JMenuItem();
        menuNovo = new javax.swing.JMenu();
        menuNovoFuncionario = new javax.swing.JMenuItem();
        menuNovoSetor = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abaMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                abaMenuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTableRecebidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableRecebidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableRecebidosFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRecebidos);

        abaMenuRecebidos.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout abaMenuRecebidosLayout = new javax.swing.GroupLayout(abaMenuRecebidos);
        abaMenuRecebidos.setLayout(abaMenuRecebidosLayout);
        abaMenuRecebidosLayout.setHorizontalGroup(
            abaMenuRecebidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        abaMenuRecebidosLayout.setVerticalGroup(
            abaMenuRecebidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        abaMenu.addTab("Recebidos", abaMenuRecebidos);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        abaMenuEnviados.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout abaMenuEnviadosLayout = new javax.swing.GroupLayout(abaMenuEnviados);
        abaMenuEnviados.setLayout(abaMenuEnviadosLayout);
        abaMenuEnviadosLayout.setHorizontalGroup(
            abaMenuEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        abaMenuEnviadosLayout.setVerticalGroup(
            abaMenuEnviadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        abaMenu.addTab("Enviados", abaMenuEnviados);

        abaMenuNovo.setBackground(new java.awt.Color(91, 91, 95));
        abaMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaMenuNovoMouseClicked(evt);
            }
        });
        abaMenuNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                abaMenuNovoKeyTyped(evt);
            }
        });

        cBDestinatario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funicionário" }));
        cBDestinatario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cBDestinatarioFocusGained(evt);
            }
        });
        cBDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBDestinatarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Destinatário :");

        jLabel2.setText("Link :");

        jTextFieldLink.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jTextFieldLink.setText("Cole o link do documento aqui.");
        jTextFieldLink.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLinkFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLinkFocusLost(evt);
            }
        });
        jTextFieldLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLinkActionPerformed(evt);
            }
        });

        abaMenuNovo.setLayer(cBDestinatario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        abaMenuNovo.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        abaMenuNovo.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        abaMenuNovo.setLayer(jTextFieldLink, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout abaMenuNovoLayout = new javax.swing.GroupLayout(abaMenuNovo);
        abaMenuNovo.setLayout(abaMenuNovoLayout);
        abaMenuNovoLayout.setHorizontalGroup(
            abaMenuNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMenuNovoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(abaMenuNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(cBDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        abaMenuNovoLayout.setVerticalGroup(
            abaMenuNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaMenuNovoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        abaMenu.addTab("Novo Envio", abaMenuNovo);

        menuArquivo.setText("Arquivo");

        menuArquivoNovoProtocolo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuArquivoNovoProtocolo.setText("Novo Protocolo");
        menuArquivo.add(menuArquivoNovoProtocolo);

        menuArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuArquivoSair.setText("Sair");
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuEditar.setText("Editar");

        menuEditarFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuEditarFuncionario.setText("Funcionário");
        menuEditar.add(menuEditarFuncionario);

        menuEditarSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuEditarSetor.setText("Setor");
        menuEditarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarSetorActionPerformed(evt);
            }
        });
        menuEditar.add(menuEditarSetor);

        jMenuBar1.add(menuEditar);

        menuNovo.setText("Novo");

        menuNovoFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuNovoFuncionario.setText("Funcionário");
        menuNovoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNovoFuncionarioMouseClicked(evt);
            }
        });
        menuNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoFuncionarioActionPerformed(evt);
            }
        });
        menuNovoFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuNovoFuncionarioKeyPressed(evt);
            }
        });
        menuNovo.add(menuNovoFuncionario);

        menuNovoSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuNovoSetor.setText("Setor");
        menuNovoSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoSetorActionPerformed(evt);
            }
        });
        menuNovo.add(menuNovoSetor);

        jMenuBar1.add(menuNovo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoFuncionarioActionPerformed
    
    }//GEN-LAST:event_menuNovoFuncionarioActionPerformed

    private void abaMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_abaMenuAncestorAdded

    }//GEN-LAST:event_abaMenuAncestorAdded

    private void cBDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBDestinatarioActionPerformed

    }//GEN-LAST:event_cBDestinatarioActionPerformed

    private void jTextFieldLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLinkActionPerformed
 
    }//GEN-LAST:event_jTextFieldLinkActionPerformed

    private void jTableRecebidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableRecebidosFocusGained
        try {
            DefaultTableModel modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column
                ) {
                    return false;
                }
            };
            TableColumn c1 = new TableColumn();
            modelo.setColumnIdentifiers(new String[]{"Matricula", "Nome", "Setor"});
            
            FuncionarioDados dadosF = new FuncionarioDados();
            ArrayList<Funcionario> listaFunc = null;
            listaFunc = dadosF.listarFuncionario();
            
            for (Funcionario f1 : listaFunc) {
                modelo.addRow(new String[]{""
                    + f1.getMatricula(),
                    f1.getNomeFuncionario(),
                    f1.getSetor().getNomeSetor()});
            }
            jTableRecebidos.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jTableRecebidosFocusGained

    private void cBDestinatarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cBDestinatarioFocusGained

    }//GEN-LAST:event_cBDestinatarioFocusGained

    private void abaMenuNovoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_abaMenuNovoKeyTyped

    }//GEN-LAST:event_abaMenuNovoKeyTyped

    private void abaMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaMenuNovoMouseClicked
        cBDestinatario.requestFocus();
    }//GEN-LAST:event_abaMenuNovoMouseClicked

    private void jTextFieldLinkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLinkFocusGained
        if (jTextFieldLink.getText().equals("Cole o link do documento aqui.")) {
            jTextFieldLink.setText("");
        }
        
        if (jTextFieldLink.getText().equals("")) {
            jTextFieldLink.setFont(new Font("Tahoma", Font.PLAIN, 12));
        }
    }//GEN-LAST:event_jTextFieldLinkFocusGained

    private void jTextFieldLinkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLinkFocusLost
        if (jTextFieldLink.getText().equals("")) {
            jTextFieldLink.setFont(new Font("Tahoma", Font.ITALIC, 10));
            jTextFieldLink.setText("Cole o link do documento aqui.");
        }
        

    }//GEN-LAST:event_jTextFieldLinkFocusLost

    private void menuNovoFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuNovoFuncionarioKeyPressed
        
    }//GEN-LAST:event_menuNovoFuncionarioKeyPressed

    private void menuNovoFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNovoFuncionarioMouseClicked
       
    }//GEN-LAST:event_menuNovoFuncionarioMouseClicked

    private void menuNovoSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoSetorActionPerformed
        TelaNovoSetor novoSetor = new TelaNovoSetor();
        novoSetor.setVisible(true);
    }//GEN-LAST:event_menuNovoSetorActionPerformed

    private void menuEditarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarSetorActionPerformed
      TelaEditarSetor editarSetor = new TelaEditarSetor();
      editarSetor.setVisible(true);
    }//GEN-LAST:event_menuEditarSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaShipping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaMenu;
    private javax.swing.JDesktopPane abaMenuEnviados;
    private javax.swing.JDesktopPane abaMenuNovo;
    private javax.swing.JDesktopPane abaMenuRecebidos;
    private javax.swing.JComboBox<String> cBDestinatario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableRecebidos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldLink;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoNovoProtocolo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEditarFuncionario;
    private javax.swing.JMenuItem menuEditarSetor;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JMenuItem menuNovoFuncionario;
    private javax.swing.JMenuItem menuNovoSetor;
    // End of variables declaration//GEN-END:variables
}
